### ISSUE TITLE
ubuntu 16.0.4 , python2.7, smplx can't be installed.

### ISSUE THREAD

**Issue by LH-Abner** [nkolot/SPIN#10]
hello, I install  pyopengl in win10 with python3.6, install successfully,but  it can't be load. So I try this project in Ubuntu 16.0.4,  the pyopengl can't be install in python3.x, but python2.7 is ok , so I use python2.7. But I have a new question, the smplx is OK in python3.X， could you please help me solve this problem? Thanks!

**Comment by nkolot** [comment]
I've been using Ubuntu 18.04 and Python 3 and it works fine. Can you ellaborate more on the errors you are getting? 
As for Python 2, currently it is not supported in this repo.

**Comment by LH-Abner** [comment]
@nkolot ok,I try to install pyopengl in Ubuntu16.0.4 with python3.5,but make a error, and I can't solve, The following is the error description. 
`Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9c/1d/4544708aaa89f26c97cc09450bb333a23724a320923e74d73e028b3560f9/PyOpenGL-3.1.0.tar.gz (1.2MB)
     |████████████████████████████████| 1.2MB 2.6MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xnbu7b2_/pyopengl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xnbu7b2_/pyopengl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xnbu7b2_/pyopengl/pip-egg-info
         cwd: /tmp/pip-install-xnbu7b2_/pyopengl/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/setuptools/__init__.py", line 11, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/setuptools/extern/__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 3131, in <module>
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 3117, in _call_aside
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 3156, in _initialize_master_working_set
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 957, in subscribe
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 3156, in <lambda>
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 2656, in activate
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 2226, in declare_namespace
      File "/usr/local/lib/python3.5/dist-packages/setuptools-19.6-py3.5.egg/pkg_resources/__init__.py", line 2195, in _handle_ns
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`
