### ISSUE TITLE
Can't install nueral-renderer-pytorch 1.1.3 during pip install -r requirements.txt

### ISSUE THREAD

**Issue by eduardoLopex666** [nkolot/SPIN#112]
While installing packages in my Python 3 conda environment using 'pip install -r requirements.txt', I got the following error. 
What can be a possible solution to this dilemma?

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Public\Anaconda\envs\spin\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rukshar Alam\\AppData\\Local\\Temp\\pip-install-0nahomca\\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rukshar Alam\\AppData\\Local\\Temp\\pip-install-0nahomca\\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Rukshar Alam\AppData\Local\Temp\pip-pip-egg-info-uraoju8v'
         cwd: C:\Users\Rukshar Alam\AppData\Local\Temp\pip-install-0nahomca\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Rukshar Alam\AppData\Local\Temp\pip-install-0nahomca\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/15/28/dd59b5098e60e75948ae414ee65700597217199591dffa22797f47914702/neural_renderer_pytorch-1.1.3.tar.gz#sha256=d0d86b003c2cc1a4d8a909862fb52ff153641636471097651239764a428c9137 (from https://pypi.org/simple/neural-renderer-pytorch/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement neural-renderer-pytorch (from versions: 1.1.3)
ERROR: No matching distribution found for neural-renderer-pytorch
```

**Comment by Lruidong** [comment]
> While installing packages in my Python 3 conda environment using 'pip install -r requirements.txt', I got the following error. What can be a possible solution to this dilemma?
> 
> ```
> ERROR: Command errored out with exit status 1:
>      command: 'C:\Users\Public\Anaconda\envs\spin\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rukshar Alam\\AppData\\Local\\Temp\\pip-install-0nahomca\\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rukshar Alam\\AppData\\Local\\Temp\\pip-install-0nahomca\\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Rukshar Alam\AppData\Local\Temp\pip-pip-egg-info-uraoju8v'
>          cwd: C:\Users\Rukshar Alam\AppData\Local\Temp\pip-install-0nahomca\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Rukshar Alam\AppData\Local\Temp\pip-install-0nahomca\neural-renderer-pytorch_f6cc23a34f1243c7ab1612ec4351ce37\setup.py", line 4, in <module>
>         from torch.utils.cpp_extension import BuildExtension, CUDAExtension
>     ModuleNotFoundError: No module named 'torch'
>     ----------------------------------------
> WARNING: Discarding https://files.pythonhosted.org/packages/15/28/dd59b5098e60e75948ae414ee65700597217199591dffa22797f47914702/neural_renderer_pytorch-1.1.3.tar.gz#sha256=d0d86b003c2cc1a4d8a909862fb52ff153641636471097651239764a428c9137 (from https://pypi.org/simple/neural-renderer-pytorch/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement neural-renderer-pytorch (from versions: 1.1.3)
> ERROR: No matching distribution found for neural-renderer-pytorch
> ```

Same problem.  has anyone solved it ？

**Comment by bibibabibo26** [comment]
由于该项目用pytorch0.4.0版本，与高版本pytorch会有兼容问题，故安装编译时失败。解决该问题参考这篇博客https://blog.csdn.net/u011058765/article/details/117000663 已验证成功

**Comment by outbreak-sen** [comment]
可以参考这个CSDN博客解决，https://blog.csdn.net/axept/article/details/127359947，注意要在CPP文件中进行一些修改
