### ISSUE TITLE
Issue running demo.py

### ISSUE THREAD

**Issue by salmedina** [nkolot/SPIN#36]
Hi! Thank you for sharing your code! I have been trying to run your demo but unfortunately haven't been successful.  When I try to execute it, I get the following error:
```
python3 -u demo.py --checkpoint=data/model_checkpoint.pt --img=examples/im1010.jpg --bbox=examples/im1010_bbox.json 
Traceback (most recent call last):
  File "demo.py", line 122, in <module>
    pred_output = smpl(betas=pred_betas, body_pose=pred_rotmat[:,1:], global_orient=pred_rotmat[:,0].unsqueeze(1), pose2rot=False)
  File "/home/zal/anaconda3/envs/spin/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zal/Devel/SPIN/models/smpl.py", line 23, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/home/zal/anaconda3/envs/spin/lib/python3.7/site-packages/smplx/body_models.py", line 374, in forward
    self.lbs_weights, dtype=self.dtype)
  File "/home/zal/anaconda3/envs/spin/lib/python3.7/site-packages/smplx/lbs.py", line 195, in lbs
    pose_offsets = torch.matmul(pose_feature, posedirs) \
RuntimeError: size mismatch, m1: [1 x 639], m2: [207 x 20670] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:268
```
Got any idea of what could be happening? Thank you very much!

**Comment by nkolot** [comment]
It seems that there is an issue with SMPLX. Are you using the latest SMPLX version? If you are not, then setting pose2rot=False might not have any effect at all.

**Comment by salmedina** [comment]
Thank you so much! It works now! I had a convolusion of versions from all the packages

. For others who might deal with this problem, try installing everything in a `virtualenv` or `conda` with `Python 3.6`, as `Python 3.5` is missing some of the required packages, and `Python 3.7` might bring in newer versions of the packages which are incompatible with the current code base.

**Comment by threedlife** [comment]
@nkolot @salmedina Thank you for the answers. 

I downloaded "Version 1.0" of SMPL-X three days ago, and tried with both Python3.6 and 3.7 in virtualenv. However, it still reports dimension mismatch errors. 
```
 Traceback (most recent call last):
  File "demo.py", line 129, in <module>
    pred_output = smpl(betas=pred_betas, body_pose=pred_rotmat[:,1:], global_orient=pred_rotmat[:,0].unsqueeze(1), pose2rot=False)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/co/work/SPIN/models/smpl.py", line 23, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/smplx/body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/smplx/lbs.py", line 179, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/smplx/lbs.py", line 265, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/torch/functional.py", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2
```
Versions of dependencies are:
```
Package                 Version    
----------------------- -----------
absl-py                 0.9.0      
cachetools              4.0.0      
certifi                 2019.11.28 
chardet                 3.0.4      
chumpy                  0.69       
cycler                  0.10.0     
decorator               4.4.1      
ffnet                   0.8.4      
freetype-py             2.1.0.post1
future                  0.18.2     
google-auth             1.10.0     
google-auth-oauthlib    0.4.1      
grpcio                  1.26.0     
h5py                    2.10.0     
idna                    2.8        
imageio                 2.6.1      
kiwisolver              1.1.0      
Markdown                3.1.1      
matplotlib              3.1.2      
networkx                2.2        
neural-renderer-pytorch 1.1.3      
numpy                   1.18.1     
oauthlib                3.1.0      
opencv-python           4.1.2.30   
Pillow                  6.1.0      
pip                     19.3.1     
protobuf                3.11.2     
pyasn1                  0.4.8      
pyasn1-modules          0.2.8      
pyglet                  1.4.0b1    
PyOpenGL                3.1.0      
pyparsing               2.4.6      
pyrender                0.1.33     
python-dateutil         2.8.1      
PyWavelets              1.1.1      
requests                2.22.0     
requests-oauthlib       1.3.0      
rsa                     4.0        
scikit-image            0.16.2     
scipy                   1.0.0      
setuptools              44.0.0     
six                     1.13.0     
smplx                   0.1.13     
spacepy                 0.2.1      
tensorboard             2.0.2      
torch                   1.1.0      
torchgeometry           0.1.2      
torchvision             0.3.0      
tqdm                    4.41.1     
trimesh                 3.5.14     
urllib3                 1.25.7     
Werkzeug                0.16.0     
wheel                   0.33.6 
```

Any idea what is wrong here?
