### ISSUE TITLE
Issue with smpl model

### ISSUE THREAD

**Issue by QuteSaltyFish** [nkolot/SPIN#38]
I use the docker image that you offer, and run the fetch_data.sh script, but when I run the demo, it says that 'AssertionError: Path data/smpl does not exist!'

**Comment by geopavlakos** [comment]
You will also need to download the SMPL model. The license doesn't allow us to include the model files in the docker image. You can find more details in the [README](https://github.com/nkolot/SPIN#fetch-data).

**Comment by amituofo1996** [comment]
It's absolutely a great work.Here is some problem.

@geopavlakos after follwing your guidence, i meet this issue.

Traceback (most recent call last):
  File "demo.py", line 111, in <module>
    create_transl=False).to(device)
  File "/media/xiaofeng/E/code/SPIN-master/models/smpl.py", line 15, in __init__
    super(SMPL, self).__init__(*args, **kwargs)
  File "/home/xiaofeng/anaconda3/envs/spin/lib/python3.6/site-packages/smplx/body_models.py", line 188, in __init__
    encoding='latin1'))
_pickle.UnpicklingError: invalid load key, '?'.

Is smpl model i downloaded is broke? or smplx==0.1.12 is not compatible for this?

**Comment by shivshankar123ch** [comment]
File "C:\Users\abc\AppData\Local\Programs\Python\Python37\lib\site-packages\smplx\body_models.py", line 134, in __init__
    smpl_path)
AssertionError: Path data/body_models/smpl does not exist!
