### ISSUE TITLE
import neural_renderer Error

### ISSUE THREAD

**Issue by liren2515** [nkolot/SPIN#53]
Hi, when I tried to run the eval.py, which imports  "neural_renderer", I got the following error.

```
Traceback (most recent call last):
  File "eval.py", line 32, in <module>
    from utils.part_utils import PartRenderer
  File "/home/BaseCode/utils/part_utils.py", line 3, in <module>
    import neural_renderer as nr
  File "/usr/local/lib/python3.6/dist-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/usr/local/lib/python3.6/dist-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /usr/local/lib/python3.6/dist-packages/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6$affe26detail37_typeMetaDataInstance_preallocated_32E
```

Does anyone know how to fix this?

**Comment by nkolot** [comment]
Maybe recompile the renderer? I've noticed that if you compile a CUDAExtension in PyTorch it does not work across different pytorch versions.

**Comment by liren2515** [comment]
Fixed. Thank you.

**Comment by swerizwan** [comment]
How you fixed it?
