### ISSUE TITLE
Maybe another import neural_renderer error

### ISSUE THREAD

**Issue by ll961546784** [nkolot/SPIN#59]
I use the docker image to build environment, and use _pip install neural-renderer-pytorch_ to install the render, and It prints these:
```
Successfully built neural-renderer-pytorch
torchgeometry 0.1.1 has requirement torch==1.0.0, but you'll have torch 1.4.0 which is incompatible.
smplx 0.1.13 has requirement numpy>=1.16.2, but you'll have numpy 1.15.4 which is incompatible.
smplx 0.1.13 has requirement torchgeometry>=0.1.2, but you'll have torchgeometry 0.1.1 which is incompatible.
Installing collected packages: torch, neural-renderer-pytorch
```
after that, when I tried to run the eval.py, i got the similar error as[#53](https://github.com/nkolot/SPIN/issues/53)
```
Traceback (most recent call last):
  File "eval.py", line 32, in <module>
    from utils.part_utils import PartRenderer
  File "/test/ICPR_code/SPIN-master/utils/part_utils.py", line 3, in <module>
    import neural_renderer as nr
  File "/usr/local/lib/python3.6/dist-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/usr/local/lib/python3.6/dist-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /usr/local/lib/python3.6/dist-packages/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
```
Then, I referred to the solution, download the render's code from github and use python3 setup.py install to reinstall the render. But the problem remains

**Comment by arturbecker** [comment]
You reinstalled torch in the process. That breaks the docker container unfortunately, because the torch version therein is compiled from source.
Can you try starting a new container from the image and install the package without dependencies?

pip install neural-renderer-pytorch --no-deps
