### ISSUE TITLE
RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by willfu** [nkolot/SPIN#75]
OS: Ubuntu1604 conda env python 3.7.6
When I run the demo, it appeared as below.
(spin) will@will-pc:~/pose/SPIN$ python3 demo.py --checkpoint=data/model_checkpoint.pt --img=examples/im1010.jpg --openpose=examples/im1010_openpose.json
Traceback (most recent call last):
  File "demo.py", line 122, in <module>
    img, norm_img = process_image(args.img, args.bbox, args.openpose, input_res=constants.IMG_RES)
**_img shape is (224, 224)_**
  File "demo.py", line 97, in process_image
    img = torch.from_numpy(img).permute(2,0,1)
RuntimeError: number of dims don't match in permute

Is there any clue for that? thanks.

**Comment by willfu** [comment]
it seems the reason is related with scipy upgrade #4 @ikvision 
   new_img = scipy.resize(new_img, res)
    #new_img = scipy.misc.imresize(new_img, res)

**Comment by willfu** [comment]
it should be import skimage.transform
                   skimage.transform.resize(new_img, res)
The one ikvision mentioned could not work.
