### ISSUE TITLE
issue with colab notebook when running demo.py

### ISSUE THREAD

**Issue by YoussefAlj** [nkolot/SPIN#93]
Hi,

I have an issue when I try to run the demo.py from googlecolab notebook: when I run the block 
%%bash
python3 demo.py \
  --checkpoint=data/model_checkpoint.pt \
  --img=examples/im1010.jpg \
  --openpose=examples/im1010_openpose.json

this triggers the following error. Any idea to solve this problem?
Thanks,

Traceback (most recent call last):
  File "demo.py", line 28, in <module>
    from torchvision.transforms import Normalize
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py", line 5, in <module>
    from .inception import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/inception.py", line 6, in <module>
    from torch.jit.annotations import Optional
ImportError: cannot import name 'Optional'

**Comment by YoussefAlj** [comment]
I solved this problem by specifiying trochvision version in the requirements.txt file.
Now it looks like this (I also added pillow==6.1.0):
neural-renderer-pytorch
numpy
opencv-python
pyopengl
pyrender
scikit-image
scipy==1.0.0
tensorboard
chumpy
smplx
spacepy
torch==1.1.0
torchgeometry
torchvision==0.3.0
tqdm
trimesh
pillow==6.1.0

This raises a problem with smpl. So I modified the line 5 in SPIN/models/smpl.py  from 
from smplx.body_models import ModelOutput
to 
from smplx.body_models import SMPLXOutput

Now the problem is I guess with opengl, because I have the following error :

Traceback (most recent call last):
  File "demo.py", line 36, in <module>
    from utils.renderer import Renderer
  File "/content/SPIN/utils/renderer.py", line 6, in <module>
    import pyrender
  File "/usr/local/lib/python3.6/dist-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/usr/local/lib/python3.6/dist-packages/pyrender/light.py", line 10, in <module>
    from OpenGL.GL import *
  File "/usr/local/lib/python3.6/dist-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/local/lib/python3.6/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/usr/local/lib/python3.6/dist-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/usr/local/lib/python3.6/dist-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'


Do you know how to solve this problrem?
Regards

**Comment by nkolot** [comment]
Did you resolve this issue? I was not involved in writing the colab notebook, but it seems there seems to be an issue with OpenGL on your machine. Is our `demo.py` able to run on your machine?

**Comment by zonaylc** [comment]
Hi! I had a similar problem, and I finally found the solution!

Install torch and torchvision with the following command to make them compatible with Cuda 10.1 on Google Colab (Python 3.7):
!pip install torch==1.4.0 torchvision==0.5.0

And follow the install instruction here to make Pyrender work with OSMesa:
https://pyrender.readthedocs.io/en/latest/install/index.html#osmesa

**Comment by YoussefAlj** [comment]
Hi thanks so much for your feedback!
regards,

________________________________
De : zonaylc ***@***.***>
Envoyé : samedi 27 mars 2021 23:09
À : nkolot/SPIN ***@***.***>
Cc : YoussefAlj ***@***.***>; Author ***@***.***>
Objet : Re: [nkolot/SPIN] issue with colab notebook when running demo.py (#93)


Hi! I had a similar problem, and I finally found the solution!

Install torch and torchvision with the following command to make them compatible with Cuda 10.1 on Google Colab (Python 3.7):
!pip install torch==1.4.0 torchvision==0.5.0

And follow the install instruction here to make Pyrender work with OSMesa:
https://pyrender.readthedocs.io/en/latest/install/index.html#osmesa
